# Generated by Django 2.2.2 on 2019-07-02 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemName', models.TextField()),
                ('catNo', models.TextField(primary_key=True, serialize=False)),
                ('price', models.DateField()),
                ('quantity', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('vendorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
