# Generated by Django 2.2.2 on 2019-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.TextField(),
        ),
    ]
